# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies without running any scripts to avoid env dependent builds
RUN npm install --ignore-scripts

# Copy the rest of the source code
COPY . .

# Build the project
RUN npm run build

# Expose any necessary ports if applicable, though stdio is being used

# Set default command to run the MCP server
CMD ["node", "build/index.js"]
